<?xml version="1.0" encoding="UTF-8"?>
<TestSuiteEntity>
   <description></description>
   <name>TS01_DailyCheck Test Environments</name>
   <tag></tag>
   <isRerun>false</isRerun>
   <lastRun>2018-08-07T12:01:08</lastRun>
   <mailRecipient></mailRecipient>
   <numberOfRerun>0</numberOfRerun>
   <pageLoadTimeout>5</pageLoadTimeout>
   <pageLoadTimeoutDefault>true</pageLoadTimeoutDefault>
   <rerunFailedTestCasesOnly>false</rerunFailedTestCasesOnly>
   <testSuiteGuid>bfa07f59-6d7b-45af-8b53-919c4e5e3dab</testSuiteGuid>
   <testCaseLink>
      <guid>86435baf-9c50-47f5-9db2-eaa4d38db795</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/DailyCheck/TC01_Verify Sucessfull - Landing Aeromexico</testCaseId>
   </testCaseLink>
   <testCaseLink>
      <guid>9294759c-12f5-469e-a93d-652a3a4255af</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>false</isRun>
      <testCaseId>Test Cases/DailyCheck/TC02_Verify Sucessfull - Ajax Ktravel</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>261cb3ae-c10a-4866-ba52-d7ca0b0fa716</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>48e4cd26-f59f-4e65-b48d-d3e29b0aa13f</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>b62a3301-22aa-468e-8d11-70056a8e24d7</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>da8b7ed7-2805-4a53-b1ad-d63c2e300fb3</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>98ba5eea-721f-4ae1-affb-7188b0f4f997</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>23613493-d24a-48a3-aaa0-828147842b9d</variableId>
      </variableLink>
   </testCaseLink>
</TestSuiteEntity>
