<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>Textbox_Origen</name>
   <tag></tag>
   <elementGuidId>3694c076-d9c0-4cc9-ac6d-99324e9cb3bf</elementGuidId>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-label</name>
      <type>Main</type>
      <value>Origen</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>Autocomplete-input</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;content&quot;)/div[@class=&quot;Container&quot;]/div[1]/div[1]/div[1]/div[1]/div[@class=&quot;Content&quot;]/div[1]/main[@class=&quot;Home has-travelAdvisory&quot;]/div[1]/div[@class=&quot;HomepageBooker has-travelAdvisory is-invalid&quot;]/div[@class=&quot;FlightBooker&quot;]/div[@class=&quot;FlightBooker-inner&quot;]/div[@class=&quot;FlightBookerRouteSelector&quot;]/div[@class=&quot;FlightBookerRouteSelector&quot;]/div[@class=&quot;FlightBookerRouteItem&quot;]/div[@class=&quot;FlightBookerRouteSelector-originWrapper&quot;]/div[@class=&quot;Autocomplete&quot;]/input[@class=&quot;Autocomplete-input&quot;]</value>
   </webElementProperties>
</WebElementEntity>
